#import = ["C:\\Users\\David\\AppData\\Roaming\\alacritty\\alacritty-master\\dracula.toml"]
import = ["/home/david/.config/alacritty/dracula.toml"]

#[shell]
#program = "ubuntu"

[font]
size = 12.0
offset = { x = 1, y = 0 }

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding = { x = 5, y = 2 }
title = "Terminal"
dimensions = { columns = 105, lines = 30 }
